/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#ffffff",
        "surface": "#131313",
        "on-secondary-fixed": "#1a1c1c",
        "primary": "#ffffff",
        "on-tertiary-fixed-variant": "#474746",
        "on-primary-fixed": "#1a1c1c",
        "surface-container": "#201f1f",
        "inverse-on-surface": "#313030",
        "on-background": "#e5e2e1",
        "on-tertiary": "#313030",
        "primary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "on-primary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1c1b1b",
        "tertiary-fixed-dim": "#c8c6c5",
        "error-container": "#93000a",
        "primary-fixed-dim": "#c6c6c7",
        "inverse-primary": "#5d5f5f",
        "on-secondary-fixed-variant": "#464747",
        "on-primary-container": "#636565",
        "outline-variant": "#444748",
        "surface-container-highest": "#353534",
        "background": "#131313",
        "primary-container": "#e2e2e2",
        "on-surface": "#e5e2e1",
        "surface-tint": "#c6c6c7",
        "on-error": "#690005",
        "secondary": "#c7c6c6",
        "surface-container-high": "#2a2a2a",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#c4c7c8",
        "on-secondary-container": "#b8b8b8",
        "surface-bright": "#3a3939",
        "outline": "#8e9192",
        "error": "#ffb4ab",
        "on-tertiary-container": "#656464",
        "tertiary-container": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353534",
        "tertiary-fixed": "#e5e2e1",
        "secondary-container": "#484949",
        "on-secondary": "#2f3131",
        "surface-dim": "#131313",
        "on-primary": "#2f3131",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed": "#e3e2e2",
        "inverse-surface": "#e5e2e1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1140px",
        "stack-sm": "16px",
        "gutter": "24px",
        "stack-md": "40px",
        "unit": "4px",
        "margin-mobile": "20px",
        "stack-xl": "80px"
      },
      fontFamily: {
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-xl-mobile": ["Libre Caslon Text", "serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "headline-lg": ["Libre Caslon Text", "serif"],
        "headline-xl": ["Libre Caslon Text", "serif"],
        "body-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-xl-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
